import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { scriptLog } from '@/scripts/logger';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const migrationsDir = path.resolve(__dirname, '../electron/backend/persistence/migrations');
const outputPath = path.resolve(__dirname, '../electron/backend/persistence/generatedMigrations.ts');
const schemaMetadataOutputPath = path.resolve(__dirname, '../electron/backend/persistence/generatedSchemaMetadata.ts');
const checkOnly = process.argv.includes('--check');

function encodeTemplateLiteral(source: string): string {
    return source.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function loadMigrations(): Array<{ name: string; sql: string }> {
    const filenames = readdirSync(migrationsDir)
        .filter((filename) => filename.endsWith('.sql'))
        .sort((left, right) => left.localeCompare(right));

    if (filenames.length !== 1 || filenames[0] !== '001_runtime_baseline.sql') {
        throw new Error(
            `Alpha persistence must use exactly one canonical baseline migration: 001_runtime_baseline.sql. Found: ${filenames.join(', ')}`
        );
    }

    return filenames.map((filename) => {
        const migrationPath = path.join(migrationsDir, filename);
        const sql = readFileSync(migrationPath, 'utf8').trimEnd();
        return { name: filename, sql };
    });
}

function extractSqlNames(sql: string, pattern: RegExp): string[] {
    return Array.from(sql.matchAll(pattern), (match) => match.groups?.name)
        .filter((name): name is string => typeof name === 'string')
        .sort((left, right) => left.localeCompare(right));
}

function buildMigrationsOutput(migrations: Array<{ name: string; sql: string }>): string {
    const body = migrations
        .map(
            (migration) =>
                `    {\n` +
                `        name: '${migration.name}',\n` +
                `        sql: \`\n${encodeTemplateLiteral(migration.sql)}\n\`,\n` +
                `    },`
        )
        .join('\n');

    return [
        '// Auto-generated by scripts/generate-migrations.ts. Do not edit manually.',
        '',
        'export interface RuntimeSqlMigration {',
        '    name: string;',
        '    sql: string;',
        '}',
        '',
        'export const runtimeSqlMigrations: RuntimeSqlMigration[] = [',
        body,
        '];',
        '',
    ].join('\n');
}

function buildSchemaMetadataOutput(migrations: Array<{ name: string; sql: string }>): string {
    const baseline = migrations[0];
    if (!baseline) {
        throw new Error('Expected canonical baseline migration to generate schema metadata.');
    }

    const tables = extractSqlNames(baseline.sql, /^CREATE TABLE (?<name>[a-z0-9_]+) \(/gim);
    const indexes = extractSqlNames(baseline.sql, /^CREATE (?:UNIQUE )?INDEX (?<name>[a-z0-9_]+)\s+/gim);

    return [
        '// Auto-generated by scripts/generate-migrations.ts. Do not edit manually.',
        '',
        'export interface RuntimeSqlSchemaMetadata {',
        '    baselineMigrationName: string;',
        '    tables: string[];',
        '    indexes: string[];',
        '}',
        '',
        'export const runtimeSqlSchemaMetadata: RuntimeSqlSchemaMetadata = {',
        `    baselineMigrationName: '${baseline.name}',`,
        `    tables: ${JSON.stringify(tables, null, 4).replace(/\n/g, '\n    ')},`,
        `    indexes: ${JSON.stringify(indexes, null, 4).replace(/\n/g, '\n    ')},`,
        '};',
        '',
    ].join('\n');
}

const migrations = loadMigrations();
const nextContent = buildMigrationsOutput(migrations);
const nextSchemaMetadataContent = buildSchemaMetadataOutput(migrations);
const currentContent = existsSync(outputPath) ? readFileSync(outputPath, 'utf8') : null;
const currentSchemaMetadataContent = existsSync(schemaMetadataOutputPath)
    ? readFileSync(schemaMetadataOutputPath, 'utf8')
    : null;

if (checkOnly) {
    if (currentContent !== nextContent || currentSchemaMetadataContent !== nextSchemaMetadataContent) {
        scriptLog.error({
            tag: 'generate-migrations',
            message: 'Generated persistence artifacts are stale. Run `pnpm run generated:update`.',
        });
        process.exit(1);
    }

    scriptLog.info({
        tag: 'generate-migrations',
        message: 'generatedMigrations.ts is up to date.',
    });
    process.exit(0);
}

mkdirSync(path.dirname(outputPath), { recursive: true });
writeFileSync(outputPath, nextContent, 'utf8');
writeFileSync(schemaMetadataOutputPath, nextSchemaMetadataContent, 'utf8');
scriptLog.info({
    tag: 'generate-migrations',
    message: 'Wrote generated persistence artifact modules.',
    outputPath: path.relative(path.resolve(__dirname, '..'), outputPath),
    schemaMetadataOutputPath: path.relative(path.resolve(__dirname, '..'), schemaMetadataOutputPath),
});
