export type EntityIdPrefix =
    | 'ws'
    | 'bsel'
    | 'bcmt'
    | 'bdsn'
    | 'mem'
    | 'mrev'
    | 'mcon'
    | 'mev'
    | 'mvec'
    | 'mfact'
    | 'mlink'
    | 'medge'
    | 'chg'
    | 'thr'
    | 'sb'
    | 'mdr'
    | 'run'
    | 'outbox'
    | 'msg'
    | 'part'
    | 'media'
    | 'att'
    | 'doc'
    | 'rcpt'
    | 'rch'
    | 'tag'
    | 'sess'
    | 'csess'
    | 'perm'
    | 'ckpt'
    | 'cpr'
    | 'plan'
    | 'pvar'
    | 'pfu'
    | 'prev'
    | 'pph'
    | 'pprv'
    | 'ppi'
    | 'ppv'
    | 'ppvd'
    | 'prb'
    | 'prw'
    | 'pea'
    | 'orch'
    | 'step'
    | 'olane'
    | 'octx'
    | 'tool'
    | 'mcp'
    | 'provider'
    | 'model'
    | 'evt';

export type EntityId<P extends EntityIdPrefix = EntityIdPrefix> = `${P}_${string}`;

export function isEntityId<P extends EntityIdPrefix>(value: string, prefix: P): value is EntityId<P> {
    return value.startsWith(`${prefix}_`);
}
